# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import sys
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PrintQR(object):
    def setupUi(self, PrintQR):
        PrintQR.setObjectName("PrintQR")
        PrintQR.resize(503, 321)
        PrintQR.setAutoFillBackground(False)
        self.centralwidget = QtWidgets.QWidget(PrintQR)
        self.centralwidget.setObjectName("centralwidget")

        #Группа: база данных 
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setObjectName("groupBox")
        self.formLayout = QtWidgets.QFormLayout(self.groupBox)
        self.formLayout.setObjectName("formLayout")

        #Адрес сервера
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        #Ввод адреса сервера
        self.host = QtWidgets.QLineEdit(self.groupBox)
        self.host.setText("")
        self.host.setObjectName("host")
        self.host.setMinimumSize(QtCore.QSize(100,0))
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.host)

        #Имя пользователя
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        #Ввод имени пользователя
        self.input_user = QtWidgets.QLineEdit(self.groupBox)
        self.input_user.setObjectName("input_user")
        self.input_user.setMinimumSize(QtCore.QSize(100,0))
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.input_user)

        #Пароль пользователя 
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        #Ввод пароля пользователя
        self.input_pass = QtWidgets.QLineEdit(self.groupBox)
        self.input_pass.setObjectName("input_pass")
        self.input_pass.setMinimumSize(QtCore.QSize(100,0))
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.input_pass)

        #Группа: информация о модуле
        self.gridLayout.addWidget(self.groupBox, 0, 0, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setObjectName("groupBox_2")
        self.formLayout_2 = QtWidgets.QFormLayout(self.groupBox_2)
        self.formLayout_2.setObjectName("formLayout_2")

        #Наименование модуля
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        self.label_4.setObjectName("label_4")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_4)
        #Список имен модулей
        self.module_name = QtWidgets.QComboBox(self.groupBox_2)
        self.module_name.setObjectName("module_name")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.module_name)

        #Версия модуля
        self.label_5 = QtWidgets.QLabel(self.groupBox_2)
        self.label_5.setObjectName("label_5")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_5)
        #Список версий модулей
        self.board_ver = QtWidgets.QComboBox(self.groupBox_2)
        self.board_ver.setObjectName("board_ver")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.board_ver)

        #Версия сборки
        self.label_6 = QtWidgets.QLabel(self.groupBox_2)
        self.label_6.setObjectName("label_6")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_6)
        #Список версий сборки
        self.build_ver = QtWidgets.QComboBox(self.groupBox_2)
        self.build_ver.setObjectName("build_ver")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.build_ver)

        #Кнопка
        self.gridLayout.addWidget(self.groupBox_2, 0, 1, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setObjectName("pushButton")


        self.pushButton.clicked.connect(self.onButtonClick)
        #self.pushButton.mouseMoveEvent.connect(self.onMouseMoveEvent)
        self.gridLayout.addWidget(self.pushButton, 1, 0, 1, 2)

        self.listView = QtWidgets.QTextBrowser(self.centralwidget)
        self.listView.setObjectName("listView")
        self.gridLayout.addWidget(self.listView, 2, 0, 1, 2)
        PrintQR.setCentralWidget(self.centralwidget)

        self.retranslateUi(PrintQR)
        QtCore.QMetaObject.connectSlotsByName(PrintQR)

    def onButtonClick(self):
        text = self.listView.toPlainText()
        text += '\n' + self.host.text()
        self.listView.setText(text)

    def onMouseMoveEvent(self):
        print ('tr')


    def retranslateUi(self, PrintQR):
        _translate = QtCore.QCoreApplication.translate
        PrintQR.setWindowTitle(_translate("PrintQR", "MainWindow"))
        self.groupBox.setTitle(_translate("PrintQR", "База данных"))
        self.label.setText(_translate("PrintQR", "Адрес сервера"))
        self.label_2.setText(_translate("PrintQR", "Имя пользователя"))
        self.label_3.setText(_translate("PrintQR", "Пароль пользователя"))
        self.groupBox_2.setTitle(_translate("PrintQR", "Иформация о модуле"))
        self.label_4.setText(_translate("PrintQR", "Наименование"))
        self.label_5.setText(_translate("PrintQR", "Версия платы"))
        self.label_6.setText(_translate("PrintQR", "Версия сборки"))
        self.pushButton.setText(_translate("PrintQR", "Сгенерировать и распечатать QR-Code"))

#Тесты
if __name__ == "__main__":


    app  = QtWidgets.QApplication(sys.argv)
    main = QtWidgets.QMainWindow()
    win = Ui_PrintQR()
    # 
    win.setupUi(main)
    main.show()
    status = app.exec_()
    sys.exit(status)
